# docker-compose.yml

version: "3.8"

services:
  nextjs:
    build: .
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
